docker_repo: docker-ce.repo

# Docker user
docker_user: qmevpascua

# WEB SERVER
web_docker_img_tag: latest
web_container_name: webserver
web_ports: 3000:3000
web_dockerfile_path: docker/web/
web_docker_img_name: web

# DB SERVER
db_docker_img_name: db
db_docker_img_tag: latest
db_container_name: dbserver
db_ports: 3306:3306
db_dockerfile_path: docker/db/
